services:
  db:
    image: postgres:latest
    container_name: budgetappdb
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${SPRING_DATASOURCE_DB}
    ports: 
      - "5432:5432"
    volumes:
      - budgetapp_data:/var/lib/postgresql/data

volumes: 
  budgetapp_data: